### ISSUE TITLE
Include War Credits Unlock Cost

### ISSUE THREAD

**Issue by RobDavenport** [pencil/baunits.com#10]
Would be great to also see the War Credits unlock costs on the page. Here's the list:

| Unit              | Cost |
|-------------------|------|
| Crab              | 0    |
| Hunter            | 0    |
| Recall            | 400  |
| Recall Hunter     | 700  |
| Scorpion          | 500  |
| Beetle            | 500  |
| Blink             | 200  |
| Blink Hunter      | 400  |
| Gunbot            | 300  |
| Missilebot        | 400  |
| Wasp              | 400  |
| Hornet            | 700  |
| Ballista          | 0    |
| King Crab         | 0    |
| Crusader          | 400  |
| Bomber            | 500  |
| Shocker           | 300  |
| Recall Shocker    | 700  |
| Mortar            | 700  |
| Swift Shocker     | 400  |
| Heavy Hunter      | 700  |
| Destroyer         | 500  |
| Raider            | 500  |
| Turret            | 400  |
| Heavy Ballista    | 0    |
| Predator          | 700  |
| Sniper            | 700  |
| Advanced Recall   | 700  |
| Assaultbot        | 700  |
| Behemoth          | 500  |
| Butterfly         | 0    |
| Dragonfly         | 500  |
| Falcon            | 700  |
| Airship           | 0    |
| Advanced Recall   | 700  |
| Mammoth           | 400  |
| Stinger           | 700  |
| Heavy Turret      | 300  |
| Bulwark           | 0    |
| Katbus            | 1500 |
| Locust            | 700  |
| Kraken            | 1500 |
| Valkyrie          | 500  |
| Artillery         | 400  |
| Advancedbot       | 700  |

**Comment by pencil** [comment]
That's a great idea! Thank you for gathering all the data, I'll add it later today.

**Comment by pencil** [comment]
This is now live!

Caveat: I couldn't find the war credits icon on the Battle Aces website so I used an emoji 💰 for now…
